### ISSUE TITLE
Master To-Do list

### ISSUE THREAD

**Issue by cindy-yuting-chiu** [cindy-yuting-chiu/biostat_customer_tool#1]
# Data
- [x] Determine what things to put in the database 
- [x] Load the file to SQL database

# Back End 
## API
- [x] Build an API using FastAPI 1. GET (read the result) 2. POST (update the result)
- [x] Script that connects the API to the database: [useful resource ](https://fastapi.tiangolo.com/advanced/async-sql-databases/)
## DataBase
- [x] Build a database
- [x] Build a Doctor Table
- [x] Build a Appointment Table
- [ ] Build a Patient Table

# Front End
